services:
  caddy:
    image: caddy:2.11-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ouvrier-net

  backend:
    container_name: backend
    build:
      context: ../../../apps/backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_VERSION=/v1/api
      - PORT_LOCAL=4000
      - PORT_PROD=4000
      - PORT_STAGGING=4001
      - PORT_TEST=4002
      - API_URL_LOCAL=http://backend:4000
      - API_URL_STAGGING=http://192.162.71.169:4001
      - API_URL_TEST=http://192.162.71.169:4002
      - API_URL_PROD=http://192.162.71.169:4000
      - SECRET_TOKEN_ADMIN_LOGIN=aqwxszedcvbgfrt12^shsj@sjhjdkjjs
      - SECRET_TOKEN_PARTNER_LOGIN=abhdkskjkdjkjlks
      - GMAIL=konenonwa1998@gmail.com
      - GMAIL_PASSWORD=ibnw qeab yrmw prcs
      - MONGODB_URL_ONLINE=mongodb://mongo:27017/db_ouvrier
      - MONGODB_URL_LOCAL=mongodb://mongo:27017/db_ouvrier
    depends_on:
      - mongo
    restart: always
    ports:
      - '4000:4000'
    networks:
      - ouvrier-net

  frontend_admin:
    container_name: frontend-admin
    build:
      context: ../../../apps/frontend-admin
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always
    ports:
      - '8001:80'
    networks:
      - ouvrier-net

  frontend_public:
    container_name: frontend-public
    build:
      context: ../../../apps/frontend-public
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: always
    ports:
      - '8000:80'
    networks:
      - ouvrier-net

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo_staging:/data/db
    networks:
      - ouvrier-net

volumes:
  mongo_staging:
  caddy_data:
  caddy_config:

networks:
  ouvrier-net:
