services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.web.address=:80'
      - '--entrypoints.websecure.address=:443'
      - '--providers.docker.exposedbydefault=false'
      - '--certificatesresolvers.le.acme.email=info@ouvrierpourtout.com'
      - '--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json'
      - '--certificatesresolvers.le.acme.httpchallenge.entrypoint=web'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/letsencrypt/acme.json
    networks:
      - backend-network-ouvrier
    restart: always

  backend:
    container_name: backend
    build:
      context: ../../../apps/backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_VERSION=/v1/api
      - PORT_LOCAL=4000
      - PORT_PROD=4000
      - PORT_STAGGING=4001
      - PORT_TEST=4002
      - API_URL_LOCAL="http://backend:4000"
      - API_URL_STAGGING="http://192.162.71.169:4001"
      - API_URL_TEST="http://192.162.71.169:4002"
      - API_URL_PROD="http://192.162.71.169:4000"
      - SECRET_TOKEN_ADMIN_LOGIN="aqwxszedcvbgfrt12^shsj@sjhjdkjjs"
      - SECRET_TOKEN_PARTNER_LOGIN="abhdkskjkdjkjlks"
      - GMAIL="konenonwa1998@gmail.com"
      - GMAIL_PASSWORD="ibnw qeab yrmw prcs"
      - MONGODB_URL_ONLINE=mongodb://mongo:27017/db_ouvrier
      - MONGODB_URL_LOCAL="mongodb://mongo:27017/db_ouvrier
    env_file:
      - ../../../apps/backend/.env
    depends_on:
      - mongo
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`api.staging.ouvrierpourtout.com`)'
      - 'traefik.http.routers.backend.entrypoints=websecure'
      - 'traefik.http.routers.backend.tls.certresolver=letsencrypt'
    restart: always
    ports:
      - '4000:4000'
    networks:
      - backend-network-ouvrier
      - frontend-network-ouvrier

  frontend_admin:
    container_name: frontend-admin
    build:
      context: ../../../apps/frontend-admin
      dockerfile: Dockerfile
    depends_on:
      - backend
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend_admin.rule=Host(`admin.staging.ouvrierpourtout.com`)'
      - 'traefik.http.routers.frontend_admin.entrypoints=websecure'
      - 'traefik.http.routers.frontend_admin.tls.certresolver=letsencrypt'
    restart: always
    ports:
      - '8001:80'
    networks:
      - frontend-network-ouvrier

  frontend_public:
    container_name: frontend-public
    build:
      context: ../../../apps/frontend-public
      dockerfile: Dockerfile
    depends_on:
      - backend
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend_public.rule=Host(`staging.ouvrierpourtout.com`)'
      - 'traefik.http.routers.frontend_public.entrypoints=websecure'
      - 'traefik.http.routers.frontend_public.tls.certresolver=letsencrypt'
    restart: always
    ports:
      - '8000:80'
    networks:
      - frontend-network-ouvrier

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    depends_on:
      - traefik
    volumes:
      - mongo_staging:/data/db
    networks:
      - backend-network-ouvrier

volumes:
  mongo_staging:

networks:
  backend-network-ouvrier:
  frontend-network-ouvrier:
